import type { Vector3 } from 'three';
import type { GameState } from './GameState';

/** FROZEN shared contracts. If a contract is missing something you need, adapt inside your
 *  own module and flag it for the integrator — do not edit this file. */

export type Phase = 'menu' | 'build' | 'combat' | 'gameover';
export type Team = 'defender' | 'attacker';
export type WallTier = 1 | 2 | 3;

let nextId = 1;
export function allocId(): number {
  return nextId++;
}

// ---------- Units ----------

export interface Unit {
  id: number;
  team: Team;
  pos: Vector3; // feet position
  radius: number; // hit/collision radius
  height: number; // hit volume + health-bar anchor
  hp: number;
  maxHp: number;
  alive: boolean;
  /** Slow debuff (frost etc). Speed is multiplied by slowFactor while game.time < slowUntil. */
  slowUntil?: number;
  slowFactor?: number;
  /** Stun: the unit does nothing at all while game.time < stunUntil. Apply and test these
   *  through sim/status.ts (applyStun/isStunned/moveMultiplier) rather than by hand, so
   *  stacking rules stay consistent across abilities, towers and enemy specials. */
  stunUntil?: number;
  takeDamage(amount: number, game: GameState): void;
}

export interface Enemy extends Unit {
  defId: string;
}

export interface EnemyDef {
  id: string;
  name: string;
  hp: number;
  speed: number;
  gold: number;
  behavior: 'melee' | 'ranged' | 'boss';
  unitDamage: number; // damage per hit vs units
  attackInterval: number; // seconds between attacks
  wallDps: number; // sustained damage per second vs walls
  range: number; // attack reach (small for melee, large for ranged)
  radius: number;
  height: number;
}

// ---------- Castle ----------

export type SocketKind = 'embrasure' | 'chamber';

export interface Socket {
  id: string; // e.g. 'w1-e0' (wall 1, embrasure 0), 'w2-c1'
  kind: SocketKind;
  tier: WallTier;
  localX: number;
  worldPos: Vector3; // interaction anchor (where the player looks/stands)
  muzzlePos: Vector3; // where projectiles fire from / allies emerge (front face)
  structure: StructureInstance | null;
}

export interface Wall {
  tier: WallTier; // 1 = outermost, 3 = keep (lose the game if it falls)
  z: number; // front face z
  built: boolean;
  hp: number;
  maxHp: number;
  cost: number;
  sockets: Socket[];
}

export interface CastleApi {
  walls: Wall[]; // index 0 = tier 1 (outermost)
  /** Furthest-forward wall that is built with hp > 0 — what enemies attack. Null = keep is down. */
  outermostIntactWall(): Wall | null;
  /** Walkable ground height at (x, z): 0 on field/courtyards, wall height on intact wall tops, ramped on stairs. */
  worldHeight(x: number, z: number): number;
  canBuildWall(tier: WallTier): boolean;
  buildWall(tier: WallTier): boolean; // spends gold; emits wall:built
  repairCost(tier: WallTier): number;
  repairWall(tier: WallTier): boolean; // spends gold
  damageWall(tier: WallTier, amount: number, game: GameState): void;
  buildStructure(socketId: string, defId: string): boolean; // spends gold; emits structure:built
  upgradeStructure(socketId: string, nodeId: string): boolean; // spends gold
  getSocketById(id: string): Socket | null;
  getSocketNear(pos: Vector3, maxDist: number): Socket | null;
}

// ---------- Structures ----------

export interface UpgradeNode {
  id: string;
  name: string;
  desc: string;
  cost: number;
  requires: string | null; // parent node id; null = buyable from base
  excludes?: string[]; // node ids locked out by buying this (branch exclusivity)
}

export interface StructureDef {
  id: string;
  name: string;
  desc: string;
  cost: number;
  socketKind: SocketKind;
  upgrades: UpgradeNode[];
  create(socket: Socket, game: GameState): StructureInstance;
}

export interface StructureInstance {
  defId: string;
  socketId: string;
  purchased: string[]; // owned upgrade node ids
  tick(dt: number, game: GameState): void;
  onDestroyed?(game: GameState): void; // wall fell — clean up (kill spawned allies etc.)
}

// ---------- Player classes ----------

export interface AbilityRank {
  cost: number; // gold to buy this rank (ranks[0] is free/base)
  stats: Record<string, number>;
}

export interface AbilityDef {
  id: string;
  name: string;
  desc: string;
  icon: string; // emoji, shown in HUD
  targeting: 'aimed' | 'ground';
  cooldown: number;
  castRange?: number; // max ground-target distance
  /** UI/behavior hint: 'mobility' abilities reposition their caster (blink/leap/grapple).
   *  Absent/'attack' = deals damage or otherwise affects the world, not the caster's position. */
  role?: 'attack' | 'mobility';
  /** Additive, optional (ability-mechanics task, 2026-08-26 — one field only, kept minimal).
   *  Absent = today's instant-cast behavior; every ability except the archer's primary omits
   *  this, so mage/warrior/etc. are byte-for-byte unaffected. When present, casting.ts turns
   *  the fire button into hold-to-draw: mousedown starts a draw, draw progress runs 0->1 over
   *  `drawTime` seconds (driving `actionState.charge01`/`chargingId`), and mouseup looses it —
   *  cooldown starts on release, not on press. The effective power fraction passed to cast() as
   *  `stats.charge` is floored at `minRelease` (a snap-release at 0 held time still fires at
   *  `minRelease` power, never literally 0) and rises linearly to 1 at a full draw.
   *  `moveSpeedMult` (default 1 = no penalty) optionally slows the caster while drawing. */
  charge?: {
    drawTime: number;
    minRelease: number;
    moveSpeedMult?: number;
  };
  ranks: AbilityRank[];
  /** Execute the ability. caster: the casting PlayerState (so a mobility ability can move
   *  its own caster). origin: caster eye position. aimPoint: impact/target point (ground
   *  point for 'ground', aim-ray point for 'aimed'). stats: merged stats for the caster's
   *  current rank. */
  cast(
    game: GameState,
    caster: PlayerState,
    origin: Vector3,
    aimPoint: Vector3,
    stats: Record<string, number>
  ): void;
}

export interface PlayerClassDef {
  id: string;
  name: string;
  desc: string;
  maxHp: number;
  moveSpeed: number;
  primary: AbilityDef; // LMB, aimed, short cooldown
  abilities: AbilityDef[]; // hotkeys 2..n
}

export interface PlayerState extends Unit {
  classDef: PlayerClassDef;
  abilityRanks: Record<string, number>; // abilityId -> current rank index
  cooldowns: Record<string, number>; // abilityId -> game.time when ready again
  respawnAt: number | null; // game.time to respawn at, when dead
  yaw: number;
  pitch: number;
}

// ---------- Waves ----------

export interface WaveEntry {
  type: string; // enemy def id
  count: number;
  interval: number; // seconds between spawns
  delay: number; // seconds after wave start before first spawn
}

export interface WaveDef {
  entries: WaveEntry[];
}

// ---------- Projectiles ----------

export interface ProjectileSpec {
  pos: Vector3;
  vel: Vector3;
  team: Team; // hits units of the opposing team
  damage: number;
  radius: number; // projectile collision radius
  aoeRadius?: number; // >0: explodes on impact, damaging all opposing units in radius
  pierce?: number; // number of extra units it can pass through
  ttl?: number; // seconds (default 4)
  gravity?: number; // units/s² downward (default 0 = straight)
  kind: string; // render style key: 'bolt' | 'crossbow' | 'arrow' | 'fireball' | ...
  onImpact?(game: GameState, at: Vector3): void;
}

// ---------- Systems ----------

export interface System {
  /** Fixed 60 Hz sim step. Mutate GameState here only. */
  tick?(dt: number, game: GameState): void;
  /** Per animation frame. Read sim state, update visuals. Never mutate sim here. */
  render?(dt: number, game: GameState): void;
}
